pipeline:
  build:
    image: golang
    environment:
      - GOPATH=/drone
    commands:
      - go get github.com/golang/dep/...
      - go get github.com/markbates/grift
      - go get github.com/gobuffalo/buffalo/...
      - $GOPATH/bin/dep ensure
      - go test $(go list ./... | grep -v /vendor/) 
  slack:
    image: plugins/slack
    webhook: ${SLACK_WEBHOOK}
    channel: ci

services:
  postgres:
    image: postgres:9.4.5
    environment:
      - POSTGRES_DB=gcon_test
