development:
  dialect: postgres
  database: learn_development
  user: postgres
  password: postgres
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: learn_test
  user: postgres
  password: postgres
  host: 127.0.0.1

production:
  dialect: postgres
  database: learn_production
  user: postgres
  password: postgres
  host: learndb
